### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by EmmaSweeney** [zoeypeterson/edith-wharton_summer#1]
In the content.opf, the wiki link to the novel is incorrect. See here:
<meta property="se:url.encyclopedia.wikipedia">https://en.wikipedia.org/wiki/Summer</meta>
This link leads to the season.

It should be:
<meta property="se:url.encyclopedia.wikipedia">https://en.wikipedia.org/wiki/Summer_(novel)</meta>

**Comment by zoeypeterson** [comment]
Thanks for catching that! It's now fixed.
